### PR TITLE
PLANET-6583 Upgrade to Wordpress 5.9

### PR DESCRIPTION
**Pull request by comzeradd**
Ref: https://jira.greenpeace.org/browse/PLANET-6583

---

Testing this so far hasn't reveal anything new. Tested also on dev site with WPML.

### Testing

To test this locally, on a new docker-composer environment I just changed [GIT_REF](https://github.com/greenpeace/planet4-docker-compose/blob/master/docker-compose.yml#L67). On existing environment `wp-cli` should work.

### CODE REVIEW

**Comment by comzeradd** [comment]
One thing I noticed is that WP template editor is active on dev sites even when the relevant feature flag is off.

**Comment by Inwerpsel** [comment]
> One thing I noticed is that WP template editor is active on dev sites even when the relevant feature flag is off.

Yes looks like they removed the `theme_supports` flag for this, so the [feature toggle](https://github.com/greenpeace/planet4-master-theme/blob/45edad3d528dff3e6d94b36988ae014d285e9b69/src/MasterSite.php#L115-L118) has no effect anymore.

**Comment by Inwerpsel** [comment]
I don't find any documentation on what themes that previously used this need to do. No trace of it in the [main block theme setup docs](https://developer.wordpress.org/themes/block-themes/block-theme-setup/).

**Comment by comzeradd** [comment]
> One thing I noticed is that WP template editor is active on dev sites even when the relevant feature flag is off.

I opened https://github.com/greenpeace/planet4-master-theme/pull/1653 for this

**Review by Inwerpsel — APPROVED** [review]

**Pull request merged**
